spring:
  application:
    name: order-service
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
#  datasource:
#    url: jdbc:postgresql://localhost:5432/orders
#    username: anil
#    password: erias007
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
